name: Build Cross-Platform Executable

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl pandas
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed \
          --name ContactDetailsScript \
          --hidden-import=tkinter \
          --hidden-import=openpyxl \
          --hidden-import=pandas \
          rc/contact_details_registers.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ContactDetailsScript-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/ContactDetailsScript*